drop table if exists users, requests, items, bookings, comments;

create table if not exists users (
id bigint generated by default as identity not null,
name varchar(255) not null,
email varchar(255) not null,
constraint pk_user primary key (id),
constraint uq_user_email unique (email)
);

create table if not exists requests (
id bigint generated by default as identity not null,
description varchar(512) not null,
requester_id bigint not null references users (id) on delete cascade,
created timestamp without time zone not null,
constraint pk_requests primary key (id)
);

create table if not exists items (
id bigint generated by default as identity not null,
name varchar(255) not null,
description varchar(512) not null,
is_available boolean not null,
owner_id bigint not null references users (id) on delete cascade,
request_id bigint references requests (id) on delete cascade,
constraint pk_item primary key (id)
);

create table if not exists bookings (
id bigint generated by default as identity not null,
start_date timestamp without time zone not null,
end_date timestamp without time zone not null,
item_id bigint not null references items (id) on delete cascade,
booker_id bigint not null references users (id) on delete cascade,
status varchar(150),
constraint pk_booking primary key (id)
);

create table if not exists comments (
id bigint generated by default as identity not null,
text varchar(512) not null,
item_id bigint not null references items (id) on delete cascade,
author_id  bigint not null references users (id) on delete cascade,
created timestamp without time zone not null,
constraint pk_comment primary key (id)
);




